[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 2
opacity = 0.9
storymode = true

[settings.background]
background_choice = "minecraft"

[settings.tts]
choice = "streamlabspolly"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_006"

[reddit.creds]
client_id = "l393ei5GBzhb8czhWQqChA"
client_secret = "yRY5FcwgOMW7-N4_cmBuvLil1Xd_-Q"
username = "InevitableResident24"
password = "1166@omse"
2fa = false

[reddit.thread]
random = false
subreddit = "funny"
post_id = ""
max_comment_length = 250
post_lang = "en"
