
# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Packages
        run: sudo apt install ffmpeg python3 -y && pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: install playerwright
        run: |
          python3 -m playwright install
          python3 -m playwright install-deps

      - name: git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: run the program 
        run: python3 main.py

      - name: git lfs
        run: |
          sudo apt install git-lfs
          git lfs install
          git lfs track "TTS/*" "results/*" "results/funny/*"
          git lfs track

      - name: sort videos
        run: |
          cd results 
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git submodule add https://github.com/omxpro/reddit-videos.git reddit-videos 
          cd reddit-videos
          mkdir $(date +%F)
          cd ..
          cd funny
          cp * ../reddit-videos/$(date +%F)
          cd ../reddit-videos 
          git lfs install
          git lfs track "$(date +%F)/*"
          cd ..
          cd results/funny
          rm -rf *
          git add .
          git commit -m "New reddit videos from $(date +%F)"
          git push
          cd ../
          cd ../

      - name: push changes 
        run: |
          git add .
          git config http.postBuffer 524288000
          git commit -m "New Videos from $(date +%F)"
          git config --global http.version HTTP/1.1 
          git push 
          git config --global http.version HTTP/2
